# Generated by Django 5.0.6 on 2024-07-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_course_student5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student5',
            name='courses',
            field=models.ManyToManyField(to='main.course'),
        ),
    ]
