# Generated by Django 5.0.6 on 2024-07-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_student5_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default=11, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student5',
            name='usn',
            field=models.CharField(default=123, max_length=15),
            preserve_default=False,
        ),
    ]
